### ISSUE TITLE
Import of Blender bones fails with the rigged model of a mouse

### ISSUE THREAD

**Issue by lguyot** [HBPNeurorobotics/BlenderRobotDesigner#35]
Importing the native Blender segments of the mouse skeleton modified by Dimitri and Csaba results in a host of python errors.

The first of these error is:
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/toromis/.config/blender/2.79/scripts/addons/robot_designer_plugin/properties/segments.py", line 75, in updateDoF
    UpdateSegments.run(segment_name=segment_name)
  File "/home/toromis/.config/blender/2.79/scripts/addons/robot_designer_plugin/operators/segments.py", line 481, in run
    return super().run(**cls.pass_keywords())
  File "/home/toromis/.config/blender/2.79/scripts/addons/robot_designer_plugin/core/operators.py", line 215, in run
    check, messages = Condition.check_conditions(*cls._pre_conditions[cls])
KeyError: <class 'robot_designer_plugin.operators.segments.UpdateSegments'>
File "/home/toromis/.config/blender/2.79/scripts/addons/robot_designer_plugin/properties/segments.py", line 71, in updateDoF
RuntimeError: class ROBOTEDITOR_OT_udpate_model, function execute: incompatible return value , str(, Function.result expected a set, not a NoneType)

location: /usr/local/Blender/blender-2.79-linux-glibc219-x86_64/2.79/scripts/modules/bpy/ops.py:189

location: /usr/local/Blender/blender-2.79-linux-glibc219-x86_64/2.79/scripts/modules/bpy/ops.py:189
Error: RuntimeError: class ROBOTEDITOR_OT_udpate_model, function execute: incompatible return value , str(, Function.result expected a set, not a NoneType)

location: /usr/local/Blender/blender-2.79-linux-glibc219-x86_64/2.79/scripts/modules/bpy/ops.py:189

Traceback (most recent call last):
  File "/home/toromis/.config/blender/2.79/scripts/addons/robot_designer_plugin/core/operators.py", line 190, in run
    return get_registered_operator(cls)(**kwargs)
  File "/usr/local/Blender/blender-2.79-linux-glibc219-x86_64/2.79/scripts/modules/bpy/ops.py", line 189, in __call__
    ret = op_call(self.idname_py(), None, kw)
RuntimeError: Error: RuntimeError: class ROBOTEDITOR_OT_udpate_model, function execute: incompatible return value , str(, Function.result expected a set, not a NoneType)

location: /usr/local/Blender/blender-2.79-linux-glibc219-x86_64/2.79/scripts/modules/bpy/ops.py:189

**Comment by benef23** [comment]
This issue has been closed with the latest commit.
